# This workflow runs as a cron job to download the current version of the German Robert Koch Institute
# covid 19 dataset for Germany and publishes a new version of this dataset into our edelweiss
# data develop instance
name: Update Robert Koch Institute timeseries dataset

on:
  schedule:
  - cron: '15 9 * * *'


jobs:

  test:
    name: Update Robert Koch Institute dataset
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the repository
      uses: actions/checkout@master

    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.7'

    - name: Install dependencies
      working-directory: robert-koch-institut-timeseries
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: run update
      working-directory: robert-koch-institut-timeseries
      env:
        REFRESH_TOKEN: ${{ secrets.REFRESH_TOKEN }}
      run: python update-full-data.py
