# This workflow runs as a cron job to download the current version of the Our World in
# Data covid 19 dataset and publishes a new version of this dataset into our edelweiss
# data develop instance
name: Update Our World in Data dataset

on:
  schedule:
  - cron: '15 12 * * *'

jobs:

  test:
    name: Update Our World in Data dataset
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the repository
      uses: actions/checkout@master

    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.7'

    - name: Install dependencies
      working-directory: data-import-scripts
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run update
      working-directory: data-import-scripts
      env:
        REFRESH_TOKEN: ${{ secrets.REFRESH_TOKEN }}
      run: python our-world-in-data-complete.py
