# This workflow runs as a cron job to download the current version of the our world in
# data covid 19 dataset and publishes a new version of this dataset into our edelweiss
# data develop instance
name: Update our world in data complete dataset

on:
  schedule:
  - cron: '15 18 * * *'


jobs:

  test:
    name: Update our world in data complete dataset
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the repository
      uses: actions/checkout@master

    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.7'

    - name: Install dependencies
      working-directory: our-world-in-data-complete
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: run update
      working-directory: our-world-in-data-complete
      env:
        REFRESH_TOKEN: ${{ secrets.REFRESH_TOKEN }}
      run: python update-full-data.py
