# This workflow runs as a cron job to download the current version of the German New York Times
# covid 19 dataset for Germany and publishes a new version of this dataset into our edelweiss
# data develop instance
name: Update New York Times dataset

on:
  schedule:
  - cron: '15 15 * * *'


jobs:

  test:
    name: Update New York Times dataset
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the repository
      uses: actions/checkout@master

    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.7'

    - name: Install dependencies
      working-directory: data-import-scripts
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: run update
      working-directory: data-import-scripts
      env:
        REFRESH_TOKEN: ${{ secrets.REFRESH_TOKEN }}
      run: python new-york-times.py
